spring:
  datasource:
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  thymeleaf:
    cache: true

management:
  security:
    enabled: false
